dialogo1 = [
    {"nome": "Ann, a Estalajadeira", "texto":"Seja bem-vindo a Taverna das Inspirações caro viajante! O que procura?"},
    {"nome": "Jogador", "texto":"..."},
    {"nome": "Ann, a Estalajadeira", "texto":"Uma Experiência ? Claro, claro, nós temos alguns mapas que podem ajudá-lo a encontrar, mas primeiro gostaria de ver o seu Jogo. Estou curiosa para saber que tipo de Experiência você procura he he."},
    {"nome": "Jogador", "texto":"..."},
    {"nome": "Ann, a Estalajadeira", "texto":" Hum?! O que ... é um Jogo ? Espera ! Você não sabe o que é um Jogo ?! E ainda quer uma Experiência sem um ?!"},
    {"nome": "Jogador", "texto":"..."},
    {"nome": "Ann, a Estalajadeira", "texto":"Entendo... Então você não é deste reino não é? Certo ! Vou lhe explicar. Um Jogo é uma relíquia bastante preciosa nesse reino e através dela você consegue chegar no tesouro da Experiência. Cada Jogo tem seus próprios princípios que são utilizados para sua construção. Eles variam de acordo com cada um que os constroem, como por exemplo regras, objetivos, valor endógeno, imersão, interação entre outros. Com esses princípios, cada Jogo pode chegar na Experiência."},
    {"nome": "Ann, a Estalajadeira", "texto":"A Experiência é uma magia muito poderosa, capaz de mexer com as pessoas e é considerada o maior tesouro para todos os usuários de Jogos. Ela é capaz de nos proporcionar várias sensações e por isso é tão almejada nesse reino. Algumas Experiências podem nos proporcionar diversão, umas podem nos fazer fugir de nossa realidade e outras permitem que façamos o que desejarmos. São muitas as Experiências que podemos buscar."},
    {"nome": "Ann, a Estalajadeira", "texto":" Agora que você já sabe o que é um Jogo, deve construir um para conseguir sua Experiência. Você tem que planejar como quer que ele seja, essa etapa se chama Projeto. Com o Projeto feito e documentado, poderá construir seu Jogo através da Prototipação. Primeiro, vamos definir que tipo de Experiência você quer conseguir com seu Jogo. Existem jogos específicos para cada Experiência que se deseja conseguir, então escolha com sabedoria o que você deseja e eu lhe darei um mapa para ela!"},
    {"nome": "Ann, a Estalajadeira", "texto":"  Perfeito! Vamos começar os preparativos para a construção do seu Jogo. Agora você precisa dos Elementos para construir o Jogo, fale com o Rudolph, o Mago. Ele saberá como te ajudar."},
    {"alternativas":[ {"valor":"Diversão", "selecionado":false}, {"valor":"Fuga", "selecionado":false}, {"valor":"Prazer", "selecionado":false}, {"valor":"Livre Escolha", "selecionado":false}]}
];